#!/bin/bash
function greenMessage {
    echo -e "\\033[32;1m${@}\033[0m"
}

function redMessage {
    echo -e "\\033[31;1m${@}\033[0m"
}

function yellowMessage {
    echo -e "\\033[33;1m${@}\033[0m"
}

function blueMessage {
    echo -e "\\033[34;1m${@}\033[0m"
}
if [ "$1" == "start" ];
	then
		greenMessage 'Starting...'
		if screen -ls | grep -q chartGenerator;
		then
			redMessage 'Screen is already active!'
		else
			screen -AdmS chartGenerator php bot.php
			blueMessage 'Done!'
		fi
    ############################


elif [ "$1" == "stop" ];
	then


		greenMessage 'Stopping...'
		if screen -ls | grep -q chartGenerator;
		then
			screen -X -S chartGenerator quit
			blueMessage 'Done!'
		else
			redMessage 'Screen is already off!'
		fi
  fi
